### PR TITLE
fix build failure on 5.5

### PR DESCRIPTION
**Pull request by Venage5603**
noticed a build failure on unreal 5.5 when it attempts to convert uint32. so i thought i would be nice and fix it!

i tested it myself and it builds successfully

(i edited lines 216-277 and line 279. github doesn't seem to be displaying my changes properly)

Steps to reproduce:

- download visual studio tools 2.5 for unreal 5.4 from GitHub releases and add them to the plugins folder for your unreal 5.5 project

- attempt to compile your project from visual studio

- build fails and check error log. Most errors are about converting uint32

### CODE REVIEW

**Comment by Venage5603** [comment]
@microsoft-github-policy-service agree

**Comment by xilaraux** [comment]
hello @Venage5603! Thank you for contribution!

Can you, please, share steps or community ticket with repro for the problem this PR attempts to fix?
Also, could you, please, format the code so that diff is cleaner?

**Comment by Venage5603** [comment]
Yes. I just added the reproduction steps and i can format the code in about 1-2 hours. Ill leave another comment when that is done

**Comment by Venage5603** [comment]
done

**Comment by Venage5603** [comment]
nvm now its done. it incorrectly formatted before

**Comment by jmcintyre** [comment]
Was the intent to remove the |= and &= in UVSTestAdapterCommandlet::Main?

**Comment by Venage5603** [comment]
Probably

**Comment by saul-gardens-dev** [comment]
> (i edited lines 216-277 and line 279. github doesn't seem to be displaying my changes properly)
You've changed the line endings in the file. Your version uses CRLF (Windows style) and the original uses LF (Unix style). Correcting the line ending style corrects this.

I think the only fix necessary though is simply to change the `uint32` to `EAutomationTestFlags`? I *think* that compiles for me, locally, but I am still clearing up other compilation errors in upgrading. That said, this compilation error is no longer appearing for me, with that one change I suggested.

**Comment by saul-gardens-dev** [comment]
Looking at this further, it appears this other [commit](https://github.com/microsoft/vc-ue-extensions/commit/c088c5bec52a6c81d65a6067039cc7a4e4792a5d), 6 months ago, may have already fixed this issue in the `main` branch? I don't think these changes are necessary after all, but there hasn't been a new, formal release with these changes.

**Comment by Venage5603** [comment]
Ok. Thanks for letting me know. Ill just close this then

**Pull request closed without merging**
