### PR TITLE
Fix for not scanning blueprints from some plugins within project

### PR DESCRIPTION
**Pull request by markdotai**
Fix for not scanning blueprints which are child classes of a native class from a module which is not in a folder with the same name as the module.
---
When choosing which blueprints to scan the code seems to assume that every module is within a folder of the same name (as it uses the folder name to get the module name). But we have some plugins within our game project, and a lot of the modules are within folders which have a different name. E.g. "Runtime" or "Editor".
So this change instead uses the file name, and assumes it does match the module name in the format: Module.Build.cs
This works for us ... but clearly someone should verify/decide if it is appropriate for all cases ...

### CODE REVIEW

**Comment by hnrqbaggio** [comment]
Thanks for the contribution @markdotai. If you don't mind, I'd would like to setup a local repro to validate this change before we merge. Is this a good description of the repro steps?

1. Have a game/plugin module where the containing folder and the `.build.cs` file have different names
2. Have a blueprint that extends a class in that module
3. Run the scan

Is there anything else I would need to repro the problem?
Thanks!

**Comment by markdotai** [comment]
Hi :) Thanks for looking at it! That sounds a great idea - and those steps look good to me.
Like you mention, in theory it could work for a game module too but I haven't tried that. (Ours are in matching folders there!)
---
One interesting example with the scanning:
- AExamplePluginActor C++ class from ExampleModule in a plugin (within a folder called DifferentlyNamedFolder).
- AExampleGameActor C++ class derived from AExamplePluginActor in the game module.
- BP_ExamplePluginActor blueprint class derived from AExamplePluginActor.
- BP_ExampleGameActor blueprint derived from AExampleGameActor.
Then looking at the UCLASS declaration of AExamplePluginActor in Visual Studio it will show a blueprint reference for BP_ExampleGameActor and it won't show the BP_ExamplePluginActor.
---
This is roughly how our folder structure looks (so we haven't given the full name to the Editor and Runtime folders ...)
Root
-- Engine (UE source)
-- Game
---- Plugins
------ ExamplePlugin
-------- Source
---------- Editor
------------ ExamplePluginEditor.Build.cs
---------- Runtime
------------ ExamplePluginRuntime.Build.cs
---- Source
------ Project
-------- Project.Build.cs
------ ProjectEditor
-------- ProjectEditor.Build.cs

**Review by hnrqbaggio — APPROVED** [review]
Hello @markdotai. Sorry for the long delay on this PR.

The overall changes look good to me. Approved.
Thank you!

**Comment by markdotai** [comment]
Awesome, thanks for checking it! :)

**Pull request merged**
